# Generated by Django 2.0.2 on 2018-03-05 20:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_id', models.IntegerField()),
                ('measurement_date', models.DateTimeField(default=datetime.datetime.now)),
                ('kg', models.FloatField(blank=True)),
                ('body_fat_percentage', models.FloatField(blank=True)),
                ('body_water_percentage', models.FloatField(blank=True)),
                ('body_muscle_percentage', models.FloatField(blank=True)),
                ('right_bicep_size_in_cm', models.FloatField(blank=True)),
                ('left_bicep_size_in_cm', models.FloatField(blank=True)),
                ('chest_size_in_cm', models.FloatField(blank=True)),
                ('buttock_size_in_cm', models.FloatField(blank=True)),
                ('waist_size_in_cm', models.FloatField(blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'BodyMeasurements',
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_first_name', models.TextField()),
                ('contact_last_name', models.TextField()),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=20)),
                ('phone_number', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('logo', models.TextField(blank=True)),
                ('firm_type', models.CharField(choices=[('FITNESS_CENTER', 0), ('PERSONAL_TRAINER', 1)], default=0, max_length=1)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Firms',
            },
        ),
        migrations.CreateModel(
            name='FirmOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_membership_reminder_day', models.IntegerField(null=True)),
                ('theme', models.TextField(blank=True)),
                ('sms_credit', models.IntegerField(default=0)),
                ('is_remaining_membership_email_reminder_active', models.BooleanField(default=False)),
                ('is_remaining_membership_sms_reminder_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'FirmOptions',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_id', models.IntegerField()),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=30)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('gender', models.CharField(choices=[('MALE', 0), ('FEMALE', 1)], default=0, max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.TextField(blank=True, max_length=20)),
                ('city', models.TextField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_id', models.IntegerField()),
                ('begin_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('currency_code', models.CharField(max_length=3)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
            options={
                'db_table': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_id', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('REMAINING_MEMBERSHIP_REMINDER', 0), ('CAMPAIGN', 1)], default=0, max_length=1)),
                ('is_sms_sent', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member')),
            ],
            options={
                'db_table': 'NotificationHistories',
            },
        ),
        migrations.AddField(
            model_name='firm',
            name='firm_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.FirmOption'),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
    ]
