# Generated by Django 2.0.2 on 2018-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
