# Generated by Django 2.0.2 on 2018-03-03 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('backend', '0002_auto_20180303_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('birth_date', models.DateTimeField(blank=True)),
                ('gender', models.CharField(choices=[('MALE', '0'), ('FEMALE', '1')], max_length=1)),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone_number', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Members',
            },
        ),
        migrations.AlterModelTable(
            name='firm',
            table='Firms',
        ),
        migrations.AlterModelTable(
            name='firmoption',
            table='FirmOptions',
        ),
    ]
