# Generated by Django 2.0.2 on 2018-03-03 19:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20180303_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firm_id', models.IntegerField()),
                ('begin_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('currency_code', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Memberships',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='firm_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firm',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='firm',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='password',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', '0'), ('FEMALE', '1')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Member'),
        ),
    ]
