# Generated by Django 2.0.2 on 2018-03-03 14:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_first_name', models.TextField()),
                ('contact_last_name', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('phone_number', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('logo', models.TextField()),
                ('firm_type', models.CharField(choices=[('FITNESS_CENTER', '0'), ('PERSONAL_TRAINER', '1')], default=0, max_length=1)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modify_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FirmOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_membership_reminder_day', models.IntegerField(null=True)),
                ('theme', models.TextField()),
                ('sms_credit', models.IntegerField(default=0)),
                ('is_remaining_membership_email_reminder_active', models.BooleanField(default=False)),
                ('is_remaining_membership_sms_reminder_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='firm',
            name='firm_option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.FirmOption'),
        ),
    ]
